### ISSUE TITLE
Are you working at facebook as a front end engineer.

### ISSUE THREAD

**Issue by Rajesh-Royal** [yangshun/tech-interview-handbook#11]
If I want to enroll in facebook internship programme as front end developer does i need to expert at algorithms.

**Comment by yangshun** [comment]
This is not an issue related to the repository, so I'm closing this out. 

Yes, I'll be starting work at Facebook in November as a Front End Engineer. The term expert is quite subjective. I can't really speak about the process at Facebook as I have not officially started working there yet, but all engineering roles at tech companies expect certain level of competency in algorithms. I wouldn't say you need to be an expert, but I estimate that in order to pass the bar, you need to be comfortable with most Medium level questions on LeetCode.

**Comment by Rajesh-Royal** [comment]
Thanks for your reply. and sorry for spamming your repository.
