### ISSUE TITLE
Adding a list of practice sites

### ISSUE THREAD

**Issue by hkasera** [yangshun/tech-interview-handbook#25]
Hello,

This repository is great! Thanks for sharing this. I had created a github repo that lists all the various websites where people can practice algorithmic questions typically asked in interviews. It was initially for myself and then I decided to open-source it. I would like to add a reference to this repository here so, it could be helpful to the community as well. I feel it is aptly suited under the [preparing](https://github.com/yangshun/tech-interview-handbook/tree/master/preparing#mastery-through-practice) section in your repository. 

Let me know if this sounds good, I will raise a PR for this change!

Thanks,
Harshita Kasera

**Comment by yangshun** [comment]
Thanks @hkasera ! One of the goals of this repository is to curate (instead of just displaying a list of links), which would make it no different from a Google search, so we are not that keen on just adding links. However, there could be some gems that we might have missed out so I'm keen to have a look at your list. Would you mind leaving a link to the repo so that we can have a look first?

Btw there's [Hacktoberfest](https://hacktoberfest.digitalocean.com/) going on now and submitting PRs to this repo is a great way to earn the t-shirt 😎

**Comment by hkasera** [comment]
Thanks @yangshun for acknowledging this. 

Yes, what you say makes total sense. Sorry, I missed the link. [Here](https://github.com/hkasera/practice-coding) is the link to my repository. 
Currently this contains the list of popular practice websites. However, I am also planning to improve this list by adding some more content like whether it's free or paid and topics covered.

I would love to hear your suggestions/feedback on this and if you think this is a valuable add to your repository.

**Comment by yangshun** [comment]
Thanks for the link. In its current state, I'm afraid I'm not too keen to include the list because it will likely bombard the readers with more information than necessary when they already have a lot of knowledge to absorb. Personally I only used LeetCode for interview practice and IMO it is the more than sufficient. 

I would be glad to add a reference to your repository after you have added more content, e.g. analysis and comparisons. Do add on to this issue or make a PR when you do.

Thanks for the initiative! 😄
